### ISSUE TITLE
User field label saved as user meta instead of value for some field types.

### ISSUE THREAD

**Issue by ipokkel** [strangerstudios/paid-memberships-pro#2481]
**Describe the bug**
When setting options for 'radio', 'select', 'select2', and 'multiselect' field types the label instead of the value is set as the input value and saved in the usermeta table.

**To Reproduce**
1. Go to Memberships > Settings > User Fields and add a radio type field, setting numerical values with alpha-numeric labels in the Options input box and save fields.
2. Navigate to checkout page and inspect fields to view input field values.
3. Select any of the options and complete checkout.
4. Open database client and query the usermeta table to view the value saved for the field.

**Screenshots**
<img width="1165" alt="2023-05-23_13-55-48" src="https://github.com/strangerstudios/paid-memberships-pro/assets/9744519/66cdf602-1ecd-4668-b4fa-41d670bc1ed6">

<img width="599" alt="2023-05-23_13-58-33" src="https://github.com/strangerstudios/paid-memberships-pro/assets/9744519/49d35946-9cd6-482d-b3b3-1f40f057b47f">

<img width="1710" alt="2023-05-23_14-11-53" src="https://github.com/strangerstudios/paid-memberships-pro/assets/9744519/1efb70d6-5a82-4160-a0ad-513d934b5f7f">

**Expected behavior**
The _value_ option for a field to be set as the input value and saved as the _meta_value_ in the metadata table as per instructions "_One option per line. To set separate values and labels, use value:label._" set for the field options on the field creation page.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only Paid Memberships Pro plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Memberlite](https://wordpress.org/themes/memberlite/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Paid Memberships Pro Version 2.10.6
```
</details>

**Moderators**
Reference: 497808

**Comment by ipokkel** [comment]
As a temporary workaround, adding the following filter seems to help:

```PHP
add_filter( 'pmprorh_repair_non_associative_options', '__return_false' );
```

It is advised to confirm all field metadata is saved as expected.

**Comment by ipokkel** [comment]
While testing this issue with PMPro 3.4.3 I could replicate this issue. 

As the filter `pmprorh_repair_non_associative_options` is now deprecated with the `pmpro_field_repair_non_associative_options` filter the workaround for this would be 
```PHP
add_filter( 'pmpro_field_repair_non_associative_options', '__return_false' );
```
